package adapspand.proyfinal.parada;

public enum Estaciones {
	LISBOA, MADRID, BARCELONA, MARSELLA, LYON, PARIS, LUXEMBURGO, FRANKFURT, VIENA, BUDAPEST, BELGRADO, SOFIA, ESTAMBUL,
	BURDEOS, MILAN, ROMA, ZAGREB, SARAJEVO, TIRANA, ATENAS, BUCAREST, CHISINAU, KIEV,
	GLASGOW, BELFAST, DUBLIN, LIVERPOOL, LONDRES, BRUSELAS, ANTWERP, AMSTERDAM, BERLIN, VARSOVIA, LVIV,
	OSLO, ESTOCOLMO, COPENAGUE, HAMBURGO, MUNICH, ZURICH, 
	HELSINKI, TALLIN, RIGA, VILNA, PRAGA, NAPOLES
	
}
